version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "2g"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
       - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "2g"
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
      
volumes:
  postgres:
  pgadmin:
