version: "3.9"

services:
  posterior:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: posterior
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "500m"
    env_file:
      - .env
    volumes:
      - posterior:/posterior
    ports:
      - 7000:7000
    networks:
      - posterior
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: posterior-postgres
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "300m"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    networks:
       - posterior

networks:
  posterior:
    driver: bridge
      
volumes:
  posterior:
  postgres:
