version: "3.9"

services:
  osiris:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: osiris
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "500m"
    env_file:
      - .env
    ports:
      - 7000:7000
    networks:
      - osiris
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: osiris-postgres
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: "300m"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    networks:
       - osiris

networks:
  osiris:
    driver: bridge
      
volumes:
  postgres:
